-- ============================================
-- DESHABILITAR RLS EN TODAS LAS TABLAS
-- Ejecutar en Supabase SQL Editor
-- ============================================

-- Catálogos
ALTER TABLE IF EXISTS motivos_baja DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS instrumentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS medios_contacto DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS salones DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tipos_movimiento DISABLE ROW LEVEL SECURITY;

-- Tablas principales
ALTER TABLE IF EXISTS cursos DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS maestros DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS grupos DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS alumnos DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS alumnos_bajas DISABLE ROW LEVEL SECURITY;

-- Inventario
ALTER TABLE IF EXISTS grupos_articulos DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS articulos DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS movimientos_inventario_maestro DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS movimientos_inventario_detalle DISABLE ROW LEVEL SECURITY;

-- Caja y finanzas
ALTER TABLE IF EXISTS recibos DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS operaciones DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS rfc_clientes DISABLE ROW LEVEL SECURITY;

-- Exámenes
ALTER TABLE IF EXISTS programacion_examenes DISABLE ROW LEVEL SECURITY;

-- Otros
ALTER TABLE IF EXISTS usuarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS factores DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS prospectos DISABLE ROW LEVEL SECURITY;

-- Verificar que RLS está deshabilitado
SELECT schemaname, tablename, rowsecurity 
FROM pg_tables 
WHERE schemaname = 'public' 
ORDER BY tablename;
