const XLSX = require('xlsx');
const fs = require('fs');

const excelPath = "C:\\Users\\PC05\\Downloads\\Scala\\Scala tablas\\Maestros.xls";
const outputPath = "C:\\Users\\PC05\\Downloads\\Scala\\MIGRACION_MAESTROS_FINAL.sql";

try {
    const workbook = XLSX.readFile(excelPath, { cellDates: true });
    const sheetName = workbook.SheetNames[0];
    const worksheet = workbook.Sheets[sheetName];
    const data = XLSX.utils.sheet_to_json(worksheet);

    if (data.length === 0) {
        console.error("Error: No data found in Excel file.");
        process.exit(1);
    }

    let sqlContent = `-- Migration Script for Maestros (Final Version v3)\n`;
    sqlContent += `-- Generated on ${new Date().toISOString()}\n\n`;
    sqlContent += `DROP TABLE IF EXISTS maestros;\n\n`;

    // Updated Table Schema
    sqlContent += `CREATE TABLE maestros (\n`;
    sqlContent += `    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n`;
    sqlContent += `    nombre TEXT NOT NULL,\n`;
    sqlContent += `    direccion_1 TEXT,\n`;
    sqlContent += `    direccion_2 TEXT,\n`;
    sqlContent += `    porcentaje TEXT,\n`;
    sqlContent += `    fecha_ingreso TEXT,\n`;
    sqlContent += `    detalles_grado TEXT,\n`;
    sqlContent += `    telefono TEXT,\n`;
    sqlContent += `    clave TEXT UNIQUE NOT NULL,\n`;
    sqlContent += `    rfc TEXT,\n`;
    sqlContent += `    grado TEXT,\n`;
    sqlContent += `    observaciones TEXT,\n`; // Added for DELETE logic
    sqlContent += `    status TEXT DEFAULT 'activo'\n`;
    sqlContent += `);\n\n`;

    const existingKeys = new Set();

    function generateClave(nombre) {
        if (!nombre) return 'XX';
        const parts = nombre.trim().toUpperCase().replace(/[.]/g, '').split(/\s+/).filter(p => p.length > 0);
        let base = '';
        if (parts.length === 1) base = parts[0].substring(0, 2);
        else if (parts.length >= 2) base = parts[0].charAt(0) + parts[1].charAt(0);
        else base = 'XX';

        let key = base;
        let counter = 1;
        while (existingKeys.has(key)) {
            key = base + counter;
            counter++;
        }
        existingKeys.add(key);
        return key;
    }

    data.forEach(row => {
        let cols = ['nombre', 'clave', 'status'];
        let vals = [];

        // 1. Nombre
        let nombre = row['Nombre'] || row['NOMBRE'] || 'Desconocido';
        vals.push(`'${nombre.toString().replace(/'/g, "''")}'`);

        // 2. Clave
        let key = generateClave(nombre);
        vals.push(`'${key}'`);

        // 3. Status
        vals.push("'activo'");

        // 4. Direccion 1
        let dir1 = row['Direccion 1'] || row['DIRECCION 1'];
        if (dir1) {
            cols.push('direccion_1');
            vals.push(`'${dir1.toString().replace(/'/g, "''")}'`);
        }

        // 5. Direccion 2
        let dir2 = row['Direccion 2'] || row['DIRECCION 2'];
        if (dir2) {
            cols.push('direccion_2');
            vals.push(`'${dir2.toString().replace(/'/g, "''")}'`);
        }

        // 6. Porcentaje / Grado
        let porc = row['Porcentaje'] || row['PORCENTAJE'];
        if (porc !== undefined) {
            cols.push('porcentaje');
            // Also map to 'grado' if appropriate or just keep separate?
            // User form has 'grado', excel has 'porcentaje'. 
            // In loading logic we did `maestro.grado || maestro.porcentaje`.
            // Let's store in `porcentaje` as per excel, and maybe `grado` if distinct.
            vals.push(`'${porc.toString().replace(/'/g, "''")}'`);
        }

        // 7. Detalles Grado
        let det = row['Detalles Grado'] || row['DETALLES GRADO'];
        if (det) {
            cols.push('detalles_grado');
            vals.push(`'${det.toString().replace(/'/g, "''")}'`);
        }

        // 8. Fecha Ingreso
        let fechaRaw = row['Fecha de Ingreso'] || row['FECHA DE INGRESO'];
        if (fechaRaw) {
            let fechaVal = fechaRaw;
            if (fechaRaw instanceof Date) {
                fechaVal = fechaRaw.toISOString().split('T')[0];
            } else if (typeof fechaRaw === 'number') {
                const date = new Date(Math.round((fechaRaw - 25569) * 86400 * 1000));
                fechaVal = date.toISOString().split('T')[0];
            }
            cols.push('fecha_ingreso');
            vals.push(`'${fechaVal}'`);
        }

        // 9. Telefono
        let tel = row['Telefono'] || row['TELEFONO'] || row['Teléfono'] || row['TELÉFONO'];
        if (tel) {
            cols.push('telefono');
            vals.push(`'${tel.toString().replace(/'/g, "''")}'`);
        }

        // 10. RFC / Grado (Explicit headers check)
        // If Excel has 'RFC', add it. Did we see it? Diagnostic didn't show it.
        // If Excel has 'GRADO' distinct from 'PORCENTAJE', add it.
        // We'll stick to what we saw.

        sqlContent += `INSERT INTO maestros (${cols.join(', ')}) VALUES (${vals.join(', ')}) ON CONFLICT (clave) DO NOTHING;\n`;
    });

    fs.writeFileSync(outputPath, sqlContent);
    console.log(`Successfully generated SQL at ${outputPath}`);

} catch (error) {
    console.error("An error occurred:", error);
    process.exit(1);
}
