const XLSX = require('xlsx');
const fs = require('fs');
const path = require('path');

const excelPath = "C:\\Users\\PC05\\Downloads\\Scala\\Scala tablas\\Maestros.xls";
const outputPath = "C:\\Users\\PC05\\Downloads\\Scala\\MIGRACION_MAESTROS.sql";

try {
    if (!fs.existsSync(excelPath)) {
        console.error(`Error: File not found at ${excelPath}`);
        process.exit(1);
    }

    const workbook = XLSX.readFile(excelPath);
    const sheetName = workbook.SheetNames[0];
    const worksheet = workbook.Sheets[sheetName];
    const data = XLSX.utils.sheet_to_json(worksheet);

    if (data.length === 0) {
        console.error("Error: No data found in Excel file.");
        process.exit(1);
    }

    // Analyze columns to create table
    // Provided columns based on typical Maestros structure, will infer from first row
    const firstRow = data[0];
    const columns = Object.keys(firstRow).map(key => {
        // Normalize key: remove spaces, lowercase
        let cleanKey = key.trim().toLowerCase().replace(/\s+/g, '_');
        // Map common names to standard schema
        if (cleanKey === 'clave' || cleanKey === 'codigo') return { original: key, name: 'clave', type: 'TEXT UNIQUE NOT NULL' };
        if (cleanKey === 'nombre' || cleanKey === 'maestro') return { original: key, name: 'nombre', type: 'TEXT NOT NULL' };
        if (cleanKey === 'direccion' || cleanKey === 'domicilio') return { original: key, name: 'direccion', type: 'TEXT' };
        if (cleanKey === 'telefono' || cleanKey === 'celular' || cleanKey === 'tel') return { original: key, name: 'telefono', type: 'TEXT' };
        if (cleanKey === 'rfc') return { original: key, name: 'rfc', type: 'TEXT' };
        if (cleanKey === 'curp') return { original: key, name: 'curp', type: 'TEXT' };
        if (cleanKey === 'fecha_ingreso' || cleanKey === 'ingreso') return { original: key, name: 'fecha_ingreso', type: 'DATE DEFAULT CURRENT_DATE' };
        if (cleanKey === 'activo' || cleanKey === 'estatus') return { original: key, name: 'status', type: 'TEXT DEFAULT \'activo\'' };
        if (cleanKey === 'grado' || cleanKey === 'estudios') return { original: key, name: 'grado', type: 'TEXT' };
        if (cleanKey === 'instrumento' || cleanKey === 'especialidad') return { original: key, name: 'detalles_grado', type: 'TEXT' };

        return { original: key, name: cleanKey, type: 'TEXT' };
    });

    // Ensure Clave exists, if not, maybe generate? User said "NO alteres la lógica que genera las claves".
    // Creating Table SQL
    let sqlContent = `-- Migration Script for Maestros\n`;
    sqlContent += `-- Generated on ${new Date().toISOString()}\n\n`;

    sqlContent += `CREATE TABLE IF NOT EXISTS maestros (\n`;
    sqlContent += `    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n`;

    // Check if we have mapped columns, otherwise use what we found
    let colDefs = columns.map(col => `    ${col.name} ${col.type}`).join(',\n');
    sqlContent += colDefs;
    sqlContent += `\n);\n\n`;

    // INSERT Statements
    data.forEach(row => {
        let cols = [];
        let vals = [];

        columns.forEach(col => {
            let val = row[col.original];
            if (val !== undefined && val !== null) {
                cols.push(col.name);
                // Escape single quotes
                if (typeof val === 'string') {
                    // Normalize date format if needed
                    if (col.type.includes('DATE') && !isNaN(Date.parse(val))) {
                        // Assuming val is readable date string or Excel serial?
                        // If standard string like 'DD/MM/YYYY', might need conversion.
                        // For now assuming clean strings or standard formats.
                        // Attempt simple conversion for safety if it looks like a date
                    }
                    vals.push(`'${val.toString().replace(/'/g, "''")}'`);
                } else {
                    vals.push(`'${val}'`);
                }
            }
        });

        // Add defaults if missing
        if (!cols.includes('status')) {
            cols.push('status');
            vals.push("'activo'");
        }

        sqlContent += `INSERT INTO maestros (${cols.join(', ')}) VALUES (${vals.join(', ')}) ON CONFLICT (clave) DO NOTHING;\n`;
    });

    fs.writeFileSync(outputPath, sqlContent);
    console.log(`Successfully generated SQL at ${outputPath}`);
    console.log(`Columns detected: ${columns.map(c => c.name).join(', ')}`);
    console.log(`Rows processed: ${data.length}`);

} catch (error) {
    console.error("An error occurred:", error);
    process.exit(1);
}
