const XLSX = require('xlsx');
const fs = require('fs');

const excelPath = "C:\\Users\\PC05\\Downloads\\Scala\\Scala tablas\\Maestros.xls";
const outputPath = "C:\\Users\\PC05\\Downloads\\Scala\\MIGRACION_MAESTROS.sql";

try {
    const workbook = XLSX.readFile(excelPath);
    const sheetName = workbook.SheetNames[0];
    const worksheet = workbook.Sheets[sheetName];
    const data = XLSX.utils.sheet_to_json(worksheet);

    if (data.length === 0) {
        console.error("Error: No data found in Excel file.");
        process.exit(1);
    }

    // Define table structure explicitly since Excel headers might be messy
    let sqlContent = `-- Migration Script for Maestros\n`;
    sqlContent += `-- Generated on ${new Date().toISOString()}\n\n`;

    // Ensure table has all necessary columns including generated ones
    sqlContent += `CREATE TABLE IF NOT EXISTS maestros (\n`;
    sqlContent += `    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n`;
    sqlContent += `    nombre TEXT NOT NULL,\n`;
    sqlContent += `    clave TEXT UNIQUE NOT NULL,\n`;
    sqlContent += `    direccion TEXT,\n`;
    sqlContent += `    telefono TEXT,\n`;
    sqlContent += `    rfc TEXT,\n`;
    sqlContent += `    curp TEXT,\n`;
    sqlContent += `    grado TEXT,\n`; // Was 'porcentaje' in previous mapping? No, 'grado' is better.
    sqlContent += `    detalles_grado TEXT,\n`;
    sqlContent += `    fecha_ingreso DATE DEFAULT CURRENT_DATE,\n`;
    sqlContent += `    status TEXT DEFAULT 'activo'\n`;
    sqlContent += `);\n\n`;

    // Helper to generate key from name
    function generateKey(name, existingKeys) {
        if (!name) return 'Unknown';
        const parts = name.trim().toUpperCase().split(/\s+/).filter(p => p.length > 0);
        let base = '';
        if (parts.length === 1) base = parts[0].substring(0, 2);
        else if (parts.length >= 2) base = parts[0].charAt(0) + parts[1].charAt(0);

        // Ensure unique
        let key = base;
        let counter = 1;
        while (existingKeys.has(key)) {
            key = base + counter;
            counter++;
        }
        existingKeys.add(key);
        return key;
    }

    const existingKeys = new Set();

    // Determine mapping from Excel headers to DB columns
    // Headers found in diagnostic: 
    // 'NOMBRE', 'DIRECCION 1', 'DIRECCION 2', 'PORCENTAJE', 'FECHA DE INGRESO', 'DETALLES GRADO'
    // 'TELEFONO' missing? 'CLAVE' missing?

    data.forEach(row => {
        let cols = ['nombre', 'clave', 'status']; // Always insert these
        let vals = [];

        // Name
        let nombre = row['NOMBRE'] || row['Nombre'] || row['MAESTRO'] || 'Desconocido';
        vals.push(`'${nombre.replace(/'/g, "''")}'`);

        // Key creation (users rule: NO alter logic, but logic is in JS file, we need it here for migration)
        // Since input data doesn't have key, we MUST generate it to insert.
        // We will mimic the IS logic: 2 chars from name/lastname.
        let key = generateKey(nombre, existingKeys);
        vals.push(`'${key}'`);

        // Status
        vals.push("'activo'");

        // Address (Combine Dir 1 and 2)
        let dir1 = row['DIRECCION 1'] || row['Direccion 1'] || '';
        let dir2 = row['DIRECCION 2'] || row['Direccion 2'] || '';
        let fullDir = dir1;
        if (dir2) fullDir += (fullDir ? '\n' : '') + dir2;
        if (fullDir) {
            cols.push('direccion');
            vals.push(`'${fullDir.replace(/'/g, "''")}'`);
        }

        // Grado/Porcentaje?
        // Excel has 'PORCENTAJE' which is '0'. Maybe this isn't useful but let's map it if needed.
        // Excel has 'DETALLES GRADO'. Map to 'detalles_grado'.
        if (row['DETALLES GRADO']) {
            cols.push('detalles_grado');
            vals.push(`'${row['DETALLES GRADO'].toString().replace(/'/g, "''")}'`);
        }

        // Fecha Ingreso
        if (row['FECHA DE INGRESO']) {
            // Excel date usually string or serial number. 
            // If serial (e.g. 42903), need conversion?
            // JS execution environment doesn't have robust library for this without 'xlsx' parsing options.
            // But 'xlsx' usually returns raw value unless 'cellDates: true' passed.
            // Let's rely on string or raw value for now, DB is DATE type, so might fail if not proper format.
            // If it's a number (serial), Postgres won't like it for DATE.
            // Safe bet: Convert to string or check if number.
            // Excel serial 1 = 1900-01-01.
            // 42903 = approx 2017.
            let val = row['FECHA DE INGRESO'];
            if (typeof val === 'number') {
                // Convert Excel serial to JS Date
                const date = new Date(Math.round((val - 25569) * 86400 * 1000));
                const isoDate = date.toISOString().split('T')[0];
                cols.push('fecha_ingreso');
                vals.push(`'${isoDate}'`);
            } else {
                cols.push('fecha_ingreso');
                vals.push(`'${val}'`);
            }
        }

        sqlContent += `INSERT INTO maestros (${cols.join(', ')}) VALUES (${vals.join(', ')}) ON CONFLICT (clave) DO NOTHING;\n`;
    });

    fs.writeFileSync(outputPath, sqlContent);
    console.log(`Successfully generated SQL at ${outputPath}`);

} catch (error) {
    console.error("An error occurred:", error);
    process.exit(1);
}
