const XLSX = require('xlsx');
const fs = require('fs');

const excelPath = "C:\\Users\\PC05\\Downloads\\Scala\\Scala tablas\\Maestros.xls";
const outputPath = "C:\\Users\\PC05\\Downloads\\Scala\\MIGRACION_MAESTROS.sql";

try {
    const workbook = XLSX.readFile(excelPath, { cellDates: true });
    const sheetName = workbook.SheetNames[0];
    const worksheet = workbook.Sheets[sheetName];
    const data = XLSX.utils.sheet_to_json(worksheet);

    if (data.length === 0) {
        console.error("Error: No data found in Excel file.");
        process.exit(1);
    }

    let sqlContent = `-- Migration Script for Maestros\n`;
    sqlContent += `-- Generated on ${new Date().toISOString()}\n\n`;

    // Create Table logic
    sqlContent += `CREATE TABLE IF NOT EXISTS maestros (\n`;
    sqlContent += `    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n`;
    sqlContent += `    nombre TEXT NOT NULL,\n`;
    sqlContent += `    clave TEXT UNIQUE NOT NULL,\n`;
    sqlContent += `    direccion TEXT,\n`;
    sqlContent += `    telefono TEXT,\n`;
    sqlContent += `    rfc TEXT,\n`;
    sqlContent += `    curp TEXT,\n`;
    sqlContent += `    grado TEXT,\n`;
    sqlContent += `    detalles_grado TEXT,\n`;
    sqlContent += `    fecha_ingreso DATE DEFAULT CURRENT_DATE,\n`;
    sqlContent += `    status TEXT DEFAULT 'activo'\n`;
    sqlContent += `);\n\n`;

    const existingKeys = new Set();

    // Function to generate key
    function generateClave(nombre) {
        if (!nombre) return 'XX';
        const parts = nombre.trim().toUpperCase().split(/\s+/).filter(p => p.length > 0);
        let base = '';
        if (parts.length === 1) base = parts[0].substring(0, 2);
        else if (parts.length >= 2) base = parts[0].charAt(0) + parts[1].charAt(0);
        else base = 'XX';

        let key = base;
        let counter = 1;
        while (existingKeys.has(key)) {
            key = base + counter;
            counter++;
        }
        existingKeys.add(key);
        return key;
    }

    data.forEach(row => {
        let cols = ['nombre', 'clave', 'status'];
        let vals = [];

        // Name
        let nombre = row['Nombre'] || row['NOMBRE'] || 'Desconocido';
        vals.push(`'${nombre.toString().replace(/'/g, "''")}'`);

        // Key
        let key = generateClave(nombre);
        vals.push(`'${key}'`);

        // Status
        vals.push("'activo'");

        // Address
        let dir1 = row['Direccion 1'] || row['DIRECCION 1'] || '';
        let dir2 = row['Direccion 2'] || row['DIRECCION 2'] || '';
        let fullDir = [dir1, dir2].filter(d => d).join('\n');
        if (fullDir) {
            cols.push('direccion');
            vals.push(`'${fullDir.replace(/'/g, "''")}'`);
        }

        // Detalles Grado
        if (row['Detalles Grado']) {
            cols.push('detalles_grado');
            vals.push(`'${row['Detalles Grado'].toString().replace(/'/g, "''")}'`);
        }

        // Fecha Ingreso
        let fechaRaw = row['Fecha de Ingreso'] || row['FECHA DE INGRESO'];
        if (fechaRaw) {
            let fechaVal = fechaRaw;
            if (fechaRaw instanceof Date) {
                fechaVal = fechaRaw.toISOString().split('T')[0];
            } else if (typeof fechaRaw === 'number') {
                // If cellDates: true, this typically doesn't happen unless configured otherwise
                // But just in case
                const date = new Date(Math.round((fechaRaw - 25569) * 86400 * 1000));
                fechaVal = date.toISOString().split('T')[0];
            }
            cols.push('fecha_ingreso');
            vals.push(`'${fechaVal}'`);
        }

        sqlContent += `INSERT INTO maestros (${cols.join(', ')}) VALUES (${vals.join(', ')}) ON CONFLICT (clave) DO NOTHING;\n`;
    });

    fs.writeFileSync(outputPath, sqlContent);
    console.log(`Successfully generated SQL at ${outputPath}`);

} catch (error) {
    console.error("An error occurred:", error);
    process.exit(1);
}
