-- Migration Script for Maestros (Final Version v3)
-- Generated on 2026-02-13T23:23:59.994Z

DROP TABLE IF EXISTS maestros;

CREATE TABLE maestros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    direccion_1 TEXT,
    direccion_2 TEXT,
    porcentaje TEXT,
    fecha_ingreso TEXT,
    detalles_grado TEXT,
    telefono TEXT,
    clave TEXT UNIQUE NOT NULL,
    rfc TEXT,
    grado TEXT,
    observaciones TEXT,
    status TEXT DEFAULT 'activo'
);

INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('ALEJANDRINA ZAPATA', 'AZ', 'activo', 'CALLE 51 #246 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'ENGLISH MUSIC') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, detalles_grado) VALUES ('ALEJANDRO KEVIN CALIXTO ANDRADE', 'AK', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'PIANO') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('ALFREDO ZAPATA', 'AZ1', 'activo', 'CALLE 51 #246 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'PIANO PREPARATORIO') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('AMMY ALVARADO', 'AA', 'activo', 'CALLE 51 #246 X 44 Y 46', 'MERIDA  YUCATAN', 'PIANO PREPARATORIO') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('ANA ADAME LOPEZ', 'AA1', 'activo', 'CALLE 51 #246 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'VIOLIN') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('ANA SARMIENTO', 'AS', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'VIOLIN') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('ANGEL EK HAU', 'AE', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'BATERIA') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('ANTHONY BRAAYAN', 'AB', 'activo', 'CALLE 51 #246 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'CANTO') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, detalles_grado) VALUES ('ARAGON KU JAIR', 'AK1', 'activo', 'CALLE 51 #244 X 44 Y 43 ALTOS', 'DRUM KIDS') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('ARMANDO MIAM CANCHE', 'AM', 'activo', 'CALLE 151 X 58 Y 60', 'MERIDA YUCATAN', 'GUITARRA') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('ASTRID TORRES', 'AT', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'FCO DE MONTEJO', 'BABY MUSIC') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, detalles_grado) VALUES ('BARUC PELAEZ GOMEZ', 'BP', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'BP') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, detalles_grado) VALUES ('BRUNO DORANTES', 'BD', 'activo', 'CALLE 51 ~#244 X 44 Y 46', 'GUITARRA ACUSTICA') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status) VALUES ('Cristina González Lugo', 'CG', 'activo') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('DAMIAN MORENO MIRELES', 'DM', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'DRUM KIDS') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('DAVID PAT', 'DP', 'activo', 'CALLE 51 #246 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'DRUM KIDS') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('DAVID SANCHEZ UICAB', 'DS', 'activo', 'CALLE 51 #246 X 44 Y 46', 'MERIDA YUCATAN', 'PIANO INFANTIL') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('DENISSE CARVAJAL', 'DC', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'VIOLIN INFANTIL') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado, telefono) VALUES ('Diana López González', 'DL', 'activo', 'C-51 # 246 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'ESTIM. MUS. TEMP', '9 26 17 60') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado, telefono) VALUES ('DIEGO LARA', 'DL1', 'activo', 'CALLE 51 #246 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'VIOLIN INFANTIL', '9991 696895') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado, telefono) VALUES ('DIEGO S LARA', 'DS1', 'activo', 'CALKLE 51 # 456 X 44 Y 46', 'ALTOS', 'VIOLIN INFANTIL', '9991 696895') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado, telefono) VALUES ('EDUARDO CAAMAL RODRIGUEZ', 'EC', 'activo', 'CALLE 45 #489-B ENTRE 54 Y 56 CENTRO', 'MEROIDA YUCATAN', 'PIANO PREPARATORIO', '9994 583742') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('ELIAS PEREZ', 'EP', 'activo', 'CALLE 51 #244 X 44 Y 46', 'MERIDA YUCATAN', 'PIANO P') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, detalles_grado) VALUES ('ERENDIRA TREJO ARROYO', 'ET', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'CANTO INFANTIL') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado, telefono) VALUES ('FELIPE SILVA', 'FS', 'activo', 'CALLE 51 #246 X 44 Y 46', 'ALTOS', 'DRUM KIDS', '9994 586004') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado, telefono) VALUES ('FERNANDO SOLIS ALCARAZ', 'FS1', 'activo', 'CALLE 51 #244 X 44 Y 46', 'MERIDA YUCATAN', 'DRUM KIDS', '9991384814') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, detalles_grado) VALUES ('FRIDA RAMIREZ', 'FR', 'activo', 'CALLE 51 #246 X 44 Y 46 ALTOS', 'VIOLIN') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, detalles_grado) VALUES ('GABRIELA CANCHE', 'GC', 'activo', 'CALLE 51 3244 X 44 Y 46 ALTOS', 'CANTO') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, detalles_grado) VALUES ('GERARDO MENA', 'GM', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'BATERIA') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('GERMAN AVILA', 'GA', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'PIANO') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('GIOVANNA CASTAÑEDA', 'GC1', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'ENGLISH MUSIC') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('GOMEZ GONZALEZ ALDO ALEJANDRO', 'GG', 'activo', 'CALLE 51 #246 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'BATERIA') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, detalles_grado) VALUES ('GRISSEL JUAREZ', 'GJ', 'activo', 'CALLE 51 #246 X 44 Y 46 ALTOS', 'ENGLISH MUSIC') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('GUADALUPE MEJIA', 'GM1', 'activo', 'CALLE 51 #246 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'INICIACION MUSICAL') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado, telefono) VALUES ('ILSIA MENA', 'IM', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'PIANO PREPARATORIO', '9991 041195') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado, telefono) VALUES ('ILSIA MENA PALMA', 'IM1', 'activo', 'CALLE 65A X 80 Y 82 #516', 'CENTRO', 'TECLADO', '9994 495804') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('IVAN ALEXIS GARCIA', 'IA', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'BATERIA') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado, telefono) VALUES ('IVAN ALEXIS GARCIA PEREZ', 'IA1', 'activo', 'CALLE 51 #246 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'DRUM KIDS', '9992 396168') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('JAIME JESUS LARA MORENO', 'JJ', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'FRANCISCO DE MONTEJO', 'VIOLIN INF') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('JAIME LARA', 'JL', 'activo', 'CALLE 51 #246 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'VIOLIN') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('JAIRO JOSE BAAS KU', 'JJ1', 'activo', 'CALLE 51 #244 X 44 Y 46', 'MERIDA YUCATAN', 'PIANO') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado, telefono) VALUES ('JAIRO JOSUE BAAS', 'JJ2', 'activo', 'CALLE 43 #344 X 54 Y 56', 'MERIDA YUCATAN', 'PIANO PREP', '9992 728803') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('JAIRO JOSUE BAAS KU', 'JJ3', 'activo', 'CALLE 51 # 244 X 44 Y 46', 'MERIDA YUCATAN', 'PIANO PREPARATORIO') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('JAYRO JOSUE BAAS KU', 'JJ4', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'PIANO PREPARATORIO') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado, telefono) VALUES ('JESUS ESTEBAN AMBROSIO PACHECO', 'JE', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'PIANO PREPARATORIO', '9811050464') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, detalles_grado) VALUES ('JESUS FABIAN MEJIA', 'JF', 'activo', 'CALLE 51 3244 X 44 Y 46 ALTOS', 'PIANO PREPARATORIO') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('JOE ROMERO', 'JR', 'activo', 'CALLE 51 #244 X 44 Y 46', 'MERIDA YUCATAN', 'PIANO') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('JORGE JUAREZ', 'JJ5', 'activo', 'CALLE 51 #246 X 44 Y 46', 'MERIDA YUCATAN', 'DRUM KIDS') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('JUAN CARLOS BALBIN MARTINEZ', 'JC', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'DRUM KIDS') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status) VALUES ('Lizbeth', 'LI', 'activo') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado, telefono) VALUES ('LOURDES PINEDA', 'LP', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'ENGLISH MUSIC', '9991 340357') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, detalles_grado, telefono) VALUES ('LUIS FELIPE REYES LUNA', 'LF', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'PIANO', '9514080944') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('MANUEL ALEJANDRO RAMIREZ MEZA', 'MA', 'activo', 'CALLE 51 # 244 X 44 Y 46', 'MERIDA YUCATAN', 'DRUM KIDS') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('MARCO VALERA', 'MV', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'PIANO PREPARATORIO') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('MARIANA SINAI ECHEVERRIA', 'MS', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'CANTO INFANTIL') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('MARILYN RODRIGUEZ SOSA', 'MR', 'activo', 'CALLE 51 #246 X 44 Y 46', 'MERIDA YUCATAN', 'BABY MUSIC') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('MARINA VILLAJUANA', 'MV1', 'activo', 'CALLE 51 #246 X 44 Y 46', 'MERIDA YUCATAN', 'MONQUI KIDS') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, detalles_grado, telefono) VALUES ('MARLA HAYDEE NAPOLES PEREZ', 'MH', 'activo', 'CUBA', 'PIANO P', '9993 942424') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado, telefono) VALUES ('MAURICIO MOCTEZUMA', 'MM', 'activo', 'CALLE 51 #246 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'DRUM KIDS', '9992 218819') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, detalles_grado) VALUES ('MELCHOR HERRERA', 'MH1', 'activo', 'CALLE 51 #246 X 44 Y 46 ALTOS', 'TECLADO') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, detalles_grado, telefono) VALUES ('Melissa López González', 'ML', 'activo', 'MTRA. BABY MUSIC', '9438276/9995-754961') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, detalles_grado, telefono) VALUES ('MELISSA TEC', 'MT', 'activo', 'AV 51 #246 X 44 Y 46 ALTOS', 'PIANO P', '9991 383067') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('MIRIAM VAZQUEZ', 'MV2', 'activo', 'CALLE 51 #246 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'TECLADO INFANTIL') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado, telefono) VALUES ('MONICA GARCIA', 'MG', 'activo', 'CALLE 51 #246 X 44 Y 46', 'MERIDA YUCATAN', 'IMI', '9991 691656') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado, telefono) VALUES ('MONICA GUADALUPE GARCIA VAZQUEZ', 'MG1', 'activo', 'CALLE 57A #610 X 74A Y 76', 'FRACC LAS AMERICAS', 'INICIACION MUSICAL', '9991 691656') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, detalles_grado) VALUES ('PABLO ISAAC PECH HOO', 'PI', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'DRUM KIDS') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('RAUL MELENDEZ', 'RM', 'activo', 'CALLE 51 #246 X 44 Y 46', 'MERIDA YUCATAN', 'GUITARRA ELECTRICA') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('ROLDAN RAMIREZ COUOH', 'RR', 'activo', 'CALLE 51 #246 X 44 Y 46', 'MERIDA YUCATAN', 'BATERIA UNFANTIL') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('SAMUEL MEDINA', 'SM', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'PIANO INFANTIL') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('SAUL ADRIAN ARGAEZ MANZANO', 'SA', 'activo', 'CALLE 51 #244 X 44 Y 46', 'MERIDA YUCATAN', 'BATERIA INF') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('SERGIO LOPEZ', 'SL', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'PIANO PREP IND') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, detalles_grado, telefono) VALUES ('SHERYL ALEJANDRA  MARIN LUGO', 'SA1', 'activo', 'CALLE 51 ·244 X 44 Y 46 ALTOS', 'INICIACION Y EXPRESION', '9995 932676') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, detalles_grado) VALUES ('SILVIA CECILIA MORENO', 'SC', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'PIANO PREPARATORIO') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, detalles_grado) VALUES ('SOFIA CAMPOS', 'SC1', 'activo', 'CALLE 51 #246 X 44 Y 46 ALTOS', 'CANTO') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('SONIA PALMA', 'SP', 'activo', 'CALLE 51 #246 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'ENGLISH MUSIC') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status) VALUES ('Teresa', 'TE', 'activo') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado) VALUES ('VERONICA LOPEZ ORTEGA', 'VL', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'DRUM KIDS') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, detalles_grado) VALUES ('VICTOR ARMIN LOPEZ ECHEVERRIA', 'VA', 'activo', 'CALLE 51', 'DRUM KIDS') ON CONFLICT (clave) DO NOTHING;
INSERT INTO maestros (nombre, clave, status, direccion_1, direccion_2, detalles_grado, telefono) VALUES ('VICTOR MARTIN RAMIREZ', 'VM', 'activo', 'CALLE 51 #244 X 44 Y 46 ALTOS', 'MERIDA YUCATAN', 'BATERIA', '9995 972982') ON CONFLICT (clave) DO NOTHING;
