-- ==============================================================================
-- SCHEMA FOR 'CURSOS' MODULE
-- Table definition based on 'cursos.js' usage and user requirements
-- ==============================================================================

-- 1. Create table 'cursos' if it doesn't exist
CREATE TABLE IF NOT EXISTS cursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    clave TEXT UNIQUE, -- Clave (e.g., 'PP', 'GA', etc.)
    curso TEXT NOT NULL, -- Nombre del curso
    curso_siguiente TEXT, -- Nombre del siguiente curso (opcional)
    precio_mensual NUMERIC(10,2) DEFAULT 0, -- Costo
    precio_inscripcion NUMERIC(10,2) DEFAULT 0, -- Recargo / Inscripción
    iva NUMERIC(5,2) DEFAULT 0.16, -- IVA (default 16%)
    activo BOOLEAN DEFAULT true -- Soft delete logic support (though User asked for Hard Delete on button, good to have)
);

-- 2. Create index for faster search
CREATE INDEX IF NOT EXISTS idx_cursos_curso ON cursos(curso);
CREATE INDEX IF NOT EXISTS idx_cursos_clave ON cursos(clave);

-- 3. Enable RLS (and then disable it as per instructions in similar files, or keep it open)
ALTER TABLE cursos ENABLE ROW LEVEL SECURITY;

-- Policy for Public Read/Write (mimicking behavior of other tables in this local app context)
CREATE POLICY "Enable all access for all users" ON cursos
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- 4. Grant access (optional, usually handled by Supabase default roles)
GRANT ALL ON TABLE cursos TO postgres;
GRANT ALL ON TABLE cursos TO anon;
GRANT ALL ON TABLE cursos TO authenticated;
GRANT ALL ON TABLE cursos TO service_role;