-- AGREGAR COLUMNA IVA A ARTICULOS SI NO EXISTE
ALTER TABLE articulos ADD COLUMN IF NOT EXISTS iva_porcentaje DECIMAL(5,2) DEFAULT 0.00;

-- AGREGAR COLUMNAS DE IVA AL DETALLE DEL MOVIMIENTO
ALTER TABLE movimientos_inventario ADD COLUMN IF NOT EXISTS iva_importe DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE movimientos_inventario ADD COLUMN IF NOT EXISTS total_linea DECIMAL(10,2) DEFAULT 0.00;
